spring.application.name=financial_transactions

# handler exceptions
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# application.properties
spring.datasource.url=jdbc:postgresql://localhost:5432/transactiondb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect